# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #General configuration
  config.ssh.username = "admin"
  config.ssh.private_key_path = "./acit_admin_id_rsa"

  #Specifiy the base box here
  config.vm.box = "centos_base"

  #VM specific configuration
  #see : https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "machine_name" do |machine_name|
    machine_name.vm.hostname = "wp.snp.acit"
    machine_name.vm.network "forwarded_port", guest: 443, host: 50443
    machine_name.vm.network "forwarded_port", guest: 22, host: 50022
    machine_name.vm.network "forwarded_port", guest: 80, host: 50080
    #other machine configuration items go here
    machine_name.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      #all other provider configuration items go here
    end
  end

  config.vm.provision :ansible do |ansible|
    #playbook path is relative to the Vagrantfile
    ansible.playbook = "provisioning/wordpress.yml"
    ansible.inventory_path = "provisioning/hosts"
  end


end