---
- hosts: wp
  become: yes 
  vars:
    mysql_root_password: P@ssw0rd
    mysql_root_password_update: yes

  tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - firewalld:
        service: https
        permanent: yes
        immediate: yes
        state: enabled

    - firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

    - name: Enable the firewall port 80
      firewalld:
       port: 80/tcp
       state: enabled
       immediate: yes

    - name: Enable the firewall port 443
      firewalld:
        port: 443/tcp
        state: enabled
        immediate: yes

    - name: install nginx
      package:
        name: nginx
        state: present

    - name: copying config file for nginx
      copy:
        src: ./wp_setup_files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: admin
        group: admin
        mode: 0644

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: install php
      package:
        name: php
        state: present

    - name: install php-mysql
      package:
        name: php-mysql
        state: present
    - name: install php-fpm
      package:
        name: php-fpm
        state: present

    - name: copying config file for www.conf
      copy:
        src: ./wp_setup_files/www.conf
        dest: /etc/php-fpm.d/www.conf
        owner: admin
        group: admin
        mode: 0644

    - name: copying config file for php.ini
      copy:
        src: ./wp_setup_files/php.ini
        dest: /etc/php.ini
        owner: admin
        group: admin
        mode: 0644

    - name: Start php-fpm
      service:
        name: php-fpm
        state: started
        enabled: yes

    - name: install mariadb
      package:
        name: mariadb
        state: present

    - name: install mariadb server
      package:
        name: mariadb-server
        state: present

    - name: Start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: copying mariadb_security_config.sql
      copy:
        src: ./wp_setup_files/mariadb_security_config.sql
        dest: /etc/mariadb_security_config.sql
        owner: admin
        group: admin
        mode: 0644
    - name: copying wp_mariadb_config.sql
      copy:
        src: ./wp_setup_files/wp_mariadb_config.sql
        dest: /etc/wp_mariadb_config.sql
        owner: admin
        group: admin
        mode: 0644

    - name: run initial script for mariadb
      shell: mysql -u root < /etc/mariadb_security_config.sql

    - name: run second script for mariadb
      shell: mysql -u root < /etc/wp_mariadb_config.sql

    - name: restart mysql
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: Downloading WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /usr/share/nginx/html/wordpress.tar.gz
        force: yes

    - name: Extract archive
      unarchive:
        src: /usr/share/nginx/html/wordpress.tar.gz
        dest: /usr/share/nginx/html/
        copy: no
        creates: /usr/share/nginx/html/wordpress

    - name: copying wp-config
      copy:
        src: ./wp_setup_files/wp-config.php
        dest: /usr/share/nginx/html/wp-config.php
        owner: admin
        group: admin
        mode: 0644

    - name: install rsync
      package:
        name: rsync
        state: present

    - name: rsync script for mariadb
      shell: rsync -avP /usr/share/nginx/html/wordpress/ /usr/share/nginx/html/