---
# tasks file for php

- name: install php
  package:
    name: php
    state: present

- name: install php-mysql
  package:
    name: php-mysql
    state: present
- name: install php-fpm
  package:
    name: php-fpm
    state: present

- name: copying config file for www.conf
  copy:
    src: ./roles/php/files/www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: admin
    group: admin
    mode: 0644

- name: copying config file for php.ini
  copy:
    src: ./roles/php/files/php.ini
    dest: /etc/php.ini
    owner: admin
    group: admin
    mode: 0644

- name: Start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

...
