---
# tasks file for nginx

- name: nginx package install
      yum: state=present name={{ item }}
      with_items:
      - nginx
      become: true

- name: Start service nginx, if not started
  service:
    name: nginx
    state: started

- name: Enable service nginx, and not touch the state
  service:
    name: nginx
    enabled: yes
