---
# tasks file for nginx

- name: install nginx
  package:
    name: nginx
    state: present

- name: copying config file for nginx
  copy:
    src: ./roles/nginx/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: admin
    group: admin
    mode: 0644

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

...